# Generated by Django 2.2 on 2019-04-17 17:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('objectives', '0002_freeinput_user_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='NumberObjectiveMaster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('number_kind', models.CharField(max_length=1)),
                ('summary_kind', models.CharField(max_length=1)),
                ('valid_flag', models.CharField(max_length=1)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RenameField(
            model_name='freeinput',
            old_name='date_index',
            new_name='day_index',
        ),
        migrations.AddField(
            model_name='freeinput',
            name='input_status',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='freeinput',
            name='year',
            field=models.PositiveSmallIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='NumberObjectiveOutput',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveSmallIntegerField()),
                ('date_index', models.PositiveSmallIntegerField()),
                ('output_value', models.PositiveSmallIntegerField()),
                ('master_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='objectives.NumberObjectiveMaster')),
            ],
        ),
        migrations.CreateModel(
            name='NumberObjective',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveSmallIntegerField()),
                ('week_index', models.PositiveSmallIntegerField()),
                ('objective_value', models.PositiveSmallIntegerField()),
                ('master_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='objectives.NumberObjectiveMaster')),
            ],
        ),
    ]
