# Generated by Django 2.2 on 2019-04-29 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('objectives', '0003_auto_20190417_1737'),
    ]

    operations = [
        migrations.AddField(
            model_name='numberobjectiveoutput',
            name='week_index',
            field=models.PositiveSmallIntegerField(default=0),
            preserve_default=False,
        ),
    ]
