# Generated by Django 2.2 on 2019-05-04 23:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('objectives', '0006_auto_20190504_2333'),
    ]

    operations = [
        migrations.RenameField(
            model_name='freeinput',
            old_name='user_id',
            new_name='user',
        ),
    ]
