# Generated by Django 2.2 on 2019-05-06 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('objectives', '0007_auto_20190504_2334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='numberobjectivemaster',
            name='name',
            field=models.CharField(max_length=100, verbose_name='名称'),
        ),
        migrations.AlterField(
            model_name='numberobjectivemaster',
            name='number_kind',
            field=models.CharField(choices=[('N', '数値'), ('P', '時間'), ('T', '時刻')], max_length=1, verbose_name='数値種別'),
        ),
        migrations.AlterField(
            model_name='numberobjectivemaster',
            name='summary_kind',
            field=models.CharField(choices=[('S', '合計'), ('A', '平均')], max_length=1, verbose_name='集計種別'),
        ),
    ]
