# Generated by Django 2.2 on 2019-05-31 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('objectives', '0010_auto_20190531_0840'),
    ]

    operations = [
        migrations.AddField(
            model_name='numberobjectiveoutput',
            name='month',
            field=models.PositiveSmallIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='numberobjectiveoutput',
            name='year',
            field=models.PositiveSmallIntegerField(default=0),
            preserve_default=False,
        ),
    ]
