# Generated by Django 2.2 on 2019-06-25 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('objectives', '0011_auto_20190531_0905'),
    ]

    operations = [
        migrations.AddField(
            model_name='numberobjectivemaster',
            name='order',
            field=models.PositiveSmallIntegerField(default=1),
            preserve_default=False,
        ),
    ]
