# Generated by Django 2.2 on 2019-06-26 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('objectives', '0012_numberobjectivemaster_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='numberobjectivemaster',
            name='order',
            field=models.PositiveSmallIntegerField(verbose_name='表示順'),
        ),
    ]
