# Generated by Django 2.2 on 2019-06-27 05:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('objectives', '0013_auto_20190626_2245'),
    ]

    operations = [
        migrations.RenameField(
            model_name='numberobjectivemaster',
            old_name='order',
            new_name='order_index',
        ),
    ]
