# Generated by Django 2.2 on 2019-07-24 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('objectives', '0015_auto_20190712_1928'),
    ]

    operations = [
        migrations.AddField(
            model_name='numberobjective',
            name='achieve_flg',
            field=models.CharField(default='0', max_length=1),
        ),
    ]
