# Generated by Django 2.2 on 2019-07-26 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('objectives', '0016_numberobjective_achieve_flg'),
    ]

    operations = [
        migrations.AddField(
            model_name='numberobjective',
            name='consective_count',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
