# Generated by Django 2.2 on 2019-07-29 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('objectives', '0017_numberobjective_consective_count'),
    ]

    operations = [
        migrations.RenameField(
            model_name='numberobjective',
            old_name='consective_count',
            new_name='consecutive_count',
        ),
    ]
